import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.6";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      {
        global: {
          headers: { Authorization: req.headers.get("Authorization")! },
        },
      }
    );

    const { data: { user }, error: userError } = await supabaseClient.auth.getUser();

    if (userError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Check existing valid generic invites for this user
    const { data: existingInvites, error: fetchError } = await supabaseClient
      .from("contact_invites")
      .select("invite_code")
      .eq("inviter_user_id", user.id)
      .eq("status", "pending")
      .is("invited_email", null)
      .gt("expires_at", new Date().toISOString());

    if (fetchError) {
      throw fetchError;
    }

    if (existingInvites && existingInvites.length > 0) {
      // Reuse the first valid pending invite
      const code = existingInvites[0].invite_code;
      const inviteLink = `${Deno.env.get("APP_URL") || "https://agora-app-swart.vercel.app"}/convite/${code}`;
      return new Response(JSON.stringify({ link: inviteLink }), {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Check limit of 10 pending invites
    const { count, error: countError } = await supabaseClient
      .from("contact_invites")
      .select("*", { count: "exact", head: true })
      .eq("inviter_user_id", user.id)
      .eq("status", "pending");

    if (countError) throw countError;

    if (count !== null && count >= 10) {
      return new Response(JSON.stringify({ error: "Limite de convites pendentes atingido (10)." }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Create a new invite
    const { data: newInvite, error: insertError } = await supabaseClient
      .from("contact_invites")
      .insert({
        inviter_user_id: user.id,
        // invite_code is generated by the DB default encode(gen_random_bytes(6), 'hex')
      })
      .select("invite_code")
      .single();

    if (insertError) throw insertError;

    const inviteLink = `${Deno.env.get("APP_URL") || "https://agora-app-swart.vercel.app"}/convite/${newInvite.invite_code}`;
    return new Response(JSON.stringify({ link: inviteLink }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
