
[functions.sos-alert]
enabled = true
verify_jwt = true
import_map = "./functions/sos-alert/deno.json"
entrypoint = "./functions/sos-alert/index.ts"

[functions.generate-invite]
enabled = true
verify_jwt = true
import_map = "./functions/generate-invite/deno.json"
entrypoint = "./functions/generate-invite/index.ts"

[functions.accept-invite]
enabled = true
verify_jwt = true
import_map = "./functions/accept-invite/deno.json"
entrypoint = "./functions/accept-invite/index.ts"

[functions.delete-account]
enabled = true
verify_jwt = true
import_map = "./functions/delete-account/deno.json"
entrypoint = "./functions/delete-account/index.ts"

[functions.classify-alert]
enabled = true
verify_jwt = true
entrypoint = "./functions/classify-alert/index.ts"
